source 'https://github.com/CocoaPods/Specs.git'

target 'ZRTabView', :exclusive => true do
  pod "ZRTabView", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "ZRTabView", :path => "../"

  
end
